### ISSUE TITLE
esx_locales mistake

### ISSUE THREAD

**Issue by Sina30** [IamLation/lation_247robbery#2]
[    c-scripting-core] Creating script environments for lation_247robbery
[script:lation_247rob] SCRIPT ERROR: @lation_247robbery/esx_locales/en.lua:13: attempt to index a nil value (global 'Locales')
[script:lation_247rob] > fn (@lation_247robbery/esx_locales/en.lua:13)
[script:lation_247rob] SCRIPT ERROR: @lation_247robbery/esx_locales/et.lua:13: attempt to index a nil value (global 'Locales')
[script:lation_247rob] > fn (@lation_247robbery/esx_locales/et.lua:13)
[script:lation_247rob] SCRIPT ERROR: @lation_247robbery/esx_locales/fr.lua:13: attempt to index a nil value (global 'Locales')
[script:lation_247rob] > fn (@lation_247robbery/esx_locales/fr.lua:13)

**Comment by IamLation** [comment]
Hey, there is no locales included with this resource. It appears you tried adding it and got an error. Not related to the resource itself, closed.
