### ISSUE TITLE
Can not Interact with computer hack & safebox

### ISSUE THREAD

**Issue by Jerrys-C** [IamLation/lation_247robbery#3]
Register works fine, but can not Interact with compute and safebox
`for key, coords in pairs(Config.Locations.Computers) do
    local data = {
        name = 'computer' ..key,
        coords = coords,
        radius = 0.35,
        debug = Config.Debug,
        options = {
            {
                icon = Strings.Target.computerIcon,
                label = Strings.Target.computerLabel,
                canInteract = function()
                    if not activeComputer then
                        return true
                    end
                    return false
                end,
                action = InitiateComputerHack,
                onSelect = InitiateComputerHack,
                distance = 2
            }
        }
    }
    AddCircleZone(data)
end
`

**Comment by IamLation** [comment]
> Register works fine, but can not Interact with compute and safebox `for key, coords in pairs(Config.Locations.Computers) do local data = { name = 'computer' ..key, coords = coords, radius = 0.35, debug = Config.Debug, options = { { icon = Strings.Target.computerIcon, label = Strings.Target.computerLabel, canInteract = function() if not activeComputer then return true end return false end, action = InitiateComputerHack, onSelect = InitiateComputerHack, distance = 2 } } } AddCircleZone(data) end `

This is not an issue. The problem you're likely experiencing is the fact that these events work in tandem with each other, meaning, the computer will not work until the register has been successfully robbed and the safe will not work until the computer hack was successfully completed.
